/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unittest.database;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MuFin
 */
public class FormKategori1841720128Arifin extends javax.swing.JFrame {

    /**
     * Creates new form FormKategori
     */
    public FormKategori1841720128Arifin() {
        initComponents();
        tampilkanDataArifin();
        kosongkanFormArifin();
    }
    
    public void kosongkanFormArifin() {
        ktg.setText("0");
        namaKtg.setText("");
        ktr.setText("");
    }

    public void tampilkanDataArifin() {
        String[] kolom = {"ID", "Nama", "Ketarangan"};
        ArrayList<Kategori1841720128Arifin> list = new Kategori1841720128Arifin().getAllArifin();
        Object rowData[] = new Object[3];

        tblKtg.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (Kategori1841720128Arifin kat : list) {
            rowData[0] = kat.getIdkategoriArifin();
            rowData[1] = kat.getNamaArifin();
            rowData[2] = kat.getKeteranganArifin();

            ((DefaultTableModel) tblKtg.getModel()).addRow(rowData);
        }
    }

    public void cariArifin(String keyword) {
        String[] kolom = {"ID", "Nama", "Keterangan"};
        ArrayList<Kategori1841720128Arifin> list = new Kategori1841720128Arifin().searchArifin(keyword);
        Object rowData[] = new Object[3];

        this.tblKtg.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        for (Kategori1841720128Arifin kat : list) {
            rowData[0] = kat.getIdkategoriArifin();
            rowData[1] = kat.getNamaArifin();
            rowData[2] = kat.getKeteranganArifin();

            ((DefaultTableModel) this.tblKtg.getModel()).addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaKtg = new javax.swing.JTextField();
        ktr = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        searc = new javax.swing.JTextField();
        tmbhBaru = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKtg = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ktg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        tmbhBaru.setText("Tambah Baru");
        tmbhBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhBaruActionPerformed(evt);
            }
        });

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tblKtg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKtg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKtgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKtg);

        jLabel1.setText("ID kategori");

        jLabel2.setText("Nama kategori");

        jLabel3.setText("Keterangan");

        ktg.setEditable(false);
        ktg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simpan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tmbhBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searc, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ktr, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(ktg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaKtg)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ktg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaKtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ktr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbhBaru)
                    .addComponent(hapus)
                    .addComponent(searc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Kategori1841720128Arifin kat = new Kategori1841720128Arifin();
        kat.setIdkategoriArifin(Integer.parseInt(this.ktg.getText()));
        kat.setNamaArifin(this.namaKtg.getText());
        kat.setKeteranganArifin(this.ktr.getText());
        kat.saveArifin();
        this.ktg.setText(Integer.toString(kat.getIdkategoriArifin()));
        tampilkanDataArifin();
    }//GEN-LAST:event_simpanActionPerformed

    private void tmbhBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhBaruActionPerformed
        // TODO add your handling code here:
        kosongkanFormArifin();
    }//GEN-LAST:event_tmbhBaruActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        cariArifin(searc.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblKtg.getModel();
        int row = tblKtg.getSelectedRow();

        Kategori1841720128Arifin kat = new Kategori1841720128Arifin().getByIdArifin(Integer.parseInt(model.getValueAt(row, 0).toString()));
        kat.deleteArifin();
        kosongkanFormArifin();
        tampilkanDataArifin();
    }//GEN-LAST:event_hapusActionPerformed

    private void tblKtgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKtgMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.tblKtg.getModel();
        int row = this.tblKtg.getSelectedRow();

        this.ktg.setText(model.getValueAt(row, 0).toString());
        this.namaKtg.setText(model.getValueAt(row, 1).toString());
        this.ktr.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblKtgMouseClicked

    private void ktgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKategori1841720128Arifin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKategori1841720128Arifin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKategori1841720128Arifin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKategori1841720128Arifin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKategori1841720128Arifin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ktg;
    private javax.swing.JTextField ktr;
    private javax.swing.JTextField namaKtg;
    private javax.swing.JTextField searc;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tblKtg;
    private javax.swing.JButton tmbhBaru;
    // End of variables declaration//GEN-END:variables
}
